### PR TITLE
Fixed mysqli query bugs for graphs, added extra crypt functions for PHP5.5+ compatibility

### PR DESCRIPTION
**Pull request by styelz**
- PHP: Increased the size of the stats graph for spam rules stats.
- PHP/Mysql: Fixed issues with prepared and non prepared MySQL statements so graphs display without a 500 error.
- PHP: replaced scrypt with password_hash/verify and crypt function to allow it to work with PHP versions that no longer support scrypt.

### CODE REVIEW

**Comment by technion** [comment]
Hi,

Thanks for this PR. Can you confirm what version of PHP you are testing this with? I haven't previously confirmed PHP7 operation, and password_hash generally assumes it.

I'm concerned about upgrade path though. People applying this patch with existing scrypt platforms will suddenly break.

**Comment by styelz** [comment]
Hey, I've tested on php7.0 and php5.6.

I will add the scrypt code back in and then make it check for a TRUE on any of them for compatibility.

I've also fixed a bug in the permissions function on configtest.php it was checking for comiled folder on the .htaccess file in there. I just used is_dir($f) for that.

Do I need to make a new PR for my new changes of can I modify this PR to re-check the latest code in my fork?

**Comment by technion** [comment]
Thanks for that. If you can add commits to your branch it should land on this PR.

**Comment by styelz** [comment]
Is there a problem with this pull request ?

**Pull request merged**
