### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by extremeshok**

### CODE REVIEW

**Comment by technion** [comment]
Hi,

This pull request is titled "enhancements", and contains no description. There are 25 commits, and nearly every commit message is "cleanup" or "update". I have no idea what's been changed but this is a diff of over 13,000 lines, which suggests a significant code divergence.

The README update refers to this being a forked product based on this repo, and I don't see how it makes sense to merge that documentation into here. It does also refer to removing the secure password storage and replacing it with an insecure MD5 hash. This is absolute negligence and I won't have any part of it.

I don't know what the goal here but I'm very much hoping you can see why I'm closing this.

**Comment by einheit** [comment]
I think he may have wanted to pull this branch instead, which consists solely of install helper scripts:
https://github.com/einheit/mailguard_install_support

**Comment by alaunay** [comment]
Why didn't you create a .spec for creating the related .rpm ? Wouldn't that be easier, managing deps, multiple packages, upgrades and such, instead of a bunch of "manual" scripts ?

**Comment by einheit** [comment]
What an interesting idea alaunay - patches are welcome!

**Comment by technion** [comment]
@alaunay If you want to make a feature request in relation to a set of scripts someone else wrote (which I will not be merging) please take it up with them.

**Comment by alaunay** [comment]
I don't care at all, I don't use any RPM based system, only Gentoo or Debian. I was just stating what seemed obvious to me...

**Comment by technion** [comment]
@alaunay If you want to state what seems obvious in relation to someone's scripts please take it up with them.

**Comment by einheit** [comment]
uh oh, someone is still sulking over the fork of their branch that was done to work on the installer. Meanwhile, mailguard servers which were quickly deployed via these scripts are doing an absolutely perfect job of quarantining spam and delivering ham. We really don't care about the drama, we're just glad to have something that works, and works well.

**Comment by technion** [comment]
@einheit I'm stating that a closed 13,000 line commit is not the place to make feature requests in relation to that fork. I'm sure you can agree having people provide feedback on your fork by commenting on a closed pull request on a repo that's not your own is not the most effective way for you to manage that communication.

**Pull request closed without merging**
